# Generated by Django 4.2.22 on 2025-07-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
