# Generated by Django 4.2.22 on 2025-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
